# Generated by Django 3.0.3 on 2020-11-28 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminpet', '0004_auto_20201125_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('dateCreate', models.DateTimeField(auto_now=True)),
                ('dateUpdated', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Category')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminpet.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='course',
            field=models.ManyToManyField(to='website.Course'),
        ),
    ]
