# Generated by Django 3.0.3 on 2020-12-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20201128_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subTitle',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
