# Generated by Django 3.0.3 on 2021-01-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_post_heardimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='heardImg',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
