# Generated by Django 3.0.3 on 2020-10-27 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='person',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bolsa.Person'),
        ),
        migrations.AddField(
            model_name='person',
            name='function',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bolsa.Function'),
        ),
        migrations.AddField(
            model_name='person',
            name='institution',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bolsa.Institution'),
        ),
    ]
