# Generated by Django 3.0.3 on 2020-12-02 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpet', '0004_auto_20201125_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='typeUser',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='adminpet.TypeUser'),
        ),
    ]
