# Generated by Django 3.0.3 on 2020-12-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpet', '0005_auto_20201202_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sexo',
            field=models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], default='F', max_length=2),
            preserve_default=False,
        ),
    ]
