# Generated by Django 3.0.3 on 2020-12-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpet', '0007_auto_20201205_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='completeName',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='typeUser',
            field=models.CharField(choices=[('T', 'Tutor'), ('P', 'Petiano')], default='P', max_length=2),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=2),
        ),
    ]
