# Generated by Django 3.0.3 on 2020-12-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpet', '0008_auto_20201205_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='sexo',
            field=models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='typeUser',
            field=models.CharField(choices=[('Tutor', 'Tutor'), ('Petiano', 'Petiano')], default='Petiano', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=20),
        ),
    ]
