# Generated by Django 3.0.3 on 2021-01-02 13:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpet', '0011_reunion_typereunion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='introduction',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='justification',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='methodology',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='objective',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
