# Generated by Django 3.0.3 on 2021-01-03 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpet', '0014_auto_20210103_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorizeduser',
            name='active',
        ),
    ]
