# Generated by Django 3.0.3 on 2021-01-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpet', '0015_remove_authorizeduser_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizeduser',
            name='completeName',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
