# Generated by Django 3.0.3 on 2021-05-02 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0002_auto_20201027_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='function',
        ),
        migrations.RemoveField(
            model_name='person',
            name='institution',
        ),
        migrations.DeleteModel(
            name='Function',
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
    ]
